services:

  django-app:
    container_name: django-app
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - 8000:8000
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge